accounts/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from django.views.generic.base import TemplateView


from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    #url(r'login/$',TemplateView.as_view(template_name='login.html'), name="login"),
    url(r'login/$',auth_views.login,{'template_name':'registration/login.html'}, name="login"),
    url(r'logout/$',auth_views.login, name="logout"),
    #path('/login',auth_views.LoginView.as_view(),name='login')
]

api/urls.py
# api/urls.py

from django.conf.urls import url, include
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns


from .views import ClientView, NetCashflowView, MovingAverageView, ClientListView
from . import views

app_name = 'api'
urlpatterns = {
    url(r'^api/client/(?P<pk>[0-9]+)/$',ClientView.as_view(), name="client"),
    url(r'^api/client/net/(?P<pk>[0-9]+)/$',NetCashflowView.as_view(), name="client_cash_flow"),
    url(r'^api/client/sma/(?P<pk>[0-9]+)/$',MovingAverageView.as_view(), name="client_sma"),
    url(r'^api/client/list/$',ClientListView.as_view(), name="client_list"),
    path('api/transaction/csv', views.import_db, name='import_db'),
}

urlpatterns = format_suffix_patterns(urlpatterns)

rest_service/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('index/',TemplateView.as_view(template_name='index.html'),name='index'),
    path('',TemplateView.as_view(template_name='home.html'),name='home'),
    path('admin/', admin.site.urls),
    url(r'^', include('api.urls')),  
    url(r'^', include('accounts.urls')),
    #path('accounts/', include('accounts.urls')),
]

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->

<head>
<meta charset="utf-8">
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Prueba Banistmo </title>
<link rel="stylesheet" href="/static/css/theme/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/theme/flexslider.css">
<link rel="stylesheet" href="/static/css/theme/main.css?v=1">
<link rel="stylesheet" href="/static/css/theme/responsive.css">
<link rel="stylesheet" href="/static/css/theme/animate.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>

<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>

<!-- JS FILES --> 
<script src="/static/js/jquery-3.2.1.min.js"></script> 
<script src="/static/js/theme/bootstrap.min.js"></script> 
<script src="/static/js/theme/jquery.flexslider-min.js"></script> 
<script src="/static/js/theme/retina.min.js"></script> 
<script src="/static/js/theme/modernizr.js"></script> 
<script src="/static/js/theme/main.js"></script>
<script type="text/javascript" src="/static/js/d3.min.js" charset="utf-8"></script>
<script type="text/javascript" src="/static/js/jquery-3.2.1.min.js" charset="utf-8"></script>

</body>
</html>

templates/base_in.html
<!-- templates/base_in.html -->
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->

<head>
<meta charset="utf-8">
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Prueba Banistmo </title>
<link rel="stylesheet" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/flexslider.css">
<link rel="stylesheet" href="/static/css/main.css?v=1">
<link rel="stylesheet" href="/static/css/responsive.css">
<link rel="stylesheet" href="/static/css/animate.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<script type="text/javascript" src="/static/js/d3.min.js" charset="utf-8"></script>
<script type="text/javascript" src="/static/js/jquery-3.2.1.min.js" charset="utf-8"></script>
</head>

<body>
    <main>
        <!-- Header Section -->
        <section class="tophead" role="tophead"> 
        <!-- Navigation Section -->
        <header id="header">
          <div class="header-content clearfix"> <a class="logo" href="#">PRUEBA BANISTMO</a>
            <nav class="navigation" role="navigation">
              <ul class="primary-nav">          
                    <LI><a href="#">Clientes</a></LI>
                    <LI><a href="#">Flujo de Caja</a></LI>
                    <LI><a href="{% url 'accounts:logout' %}">Salir</a></LI>
              </ul>
            </nav>
            <a href="#" class="nav-toggle">Menu<span></span></a> </div>
        </header>
        <!-- Navigation Section --> 
      </section>
      <!-- Header Section --> 
      <section id="header-slider" class="section">
      
      </section>
        {% block content %}
        {% endblock %}
    </main>

<!-- JS FILES --> 
<script src="/static/js/jquery-3.2.1.min.js"></script> 
<script src="/static/js/theme/bootstrap.min.js"></script> 
<script src="/static/js/theme/jquery.flexslider-min.js"></script> 
<script src="/static/js/theme/retina.min.js"></script> 
<script src="/static/js/theme/modernizr.js"></script> 
<script src="/static/js/theme/main.js"></script>


</body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'accounts:logout' %}">logout</a></p>
{% else %}
    
<!-- Header Section -->
<section class="tophead" role="tophead"> 
    <!-- Navigation Section -->
    <header id="header">
      <div class="header-content clearfix"> <a class="logo" href="#">PRUEBA BANISTMO</a>
        <nav class="navigation" role="navigation">
          <ul class="primary-nav">          
            
            <LI><a href="{% url 'accounts:login' %}">Log-in</a></LI>
          </ul>
        </nav>
        <a href="#" class="nav-toggle">Menu<span></span></a> </div>
    </header>
    <!-- Navigation Section --> 
  </section>
  <!-- Header Section --> 
  <section id="header-slider" class="section">
  
  </section>
  <!-- Service Section -->
  <section id="services" class="section services">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6 col-sm-6">
          <div class="services-content">
            <h4>¡Bienvenido!</h4>
            <p>Este es un servicio que te permitira obtener 
              información transaccional de tus clientes de manera fácil y detallada.</p>
            <p>Podrás visualizar de rápidamente cuáles han sido 
              las transacciones de cada cliente y enteder su 
              comportamiento a través de los meses</p>  
            </p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="services-content">
            <h5>Características</h5>
            <ul>
               
              <li><a href="#">Gráficos Interactivos</a></li>
              <li><a href="#">Listado Transaccional</a></li>
              <li><a href="#">Cálculo de Media Móvil</a></li>
              <li><a href="#">Autenticación de Usuarios</a></li>
                          
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="services-content">
            <h5>Tecnologías</h5>
            <ul>
              <li><a href="#">Python</a></li>
              <li><a href="#">Django</a></li>
              <li><a href="#">Django REST Framework</a></li>
              <li><a href="#">D3js</a></li>
              <li><a href="#">jQuery</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Service Section --> 
  
  <!-- footer section -->
  <footer id="contact" class="footer">
    <div class="container-fluid">
      <div class="col-md-2 left">
        <h4>Dirección</h4>
        <p> Calle 73, San Francisco.</p>
      </div>
      <div class="col-md-2 left">
        <h4>Contacto</h4>
        <p> Jahir González <br>Cel: +507-6229-4141 <br>
          Email : <a href="mailto:jago27@hotmail.com"> jago27@hotmail.com </a></p>
      </div>
      <div class="col-md-2 left">
        <h4>Social presense</h4>
        <ul class="footer-share">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          
        </ul>
      </div>
      <div class="col-md-6 right">
         </div>
    </div>
  </footer>
  <!-- footer section --> 
{% endif %}
{% endblock %}

templates/index.html
<!-- templates/home.html -->
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->

<head>
<meta charset="utf-8">
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Prueba Banistmo </title>
<link rel="stylesheet" href="/static/css/index.css">
<link rel="stylesheet" href="/static/css/theme/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/theme/flexslider.css">
<link rel="stylesheet" href="/static/css/theme/main.css?v=2">
<link rel="stylesheet" href="/static/css/theme/responsive.css">
<link rel="stylesheet" href="/static/css/theme/animate.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<script src="http://d3js.org/d3.v3.min.js"></script>
<script type="text/javascript" src="/static/js/jquery-3.2.1.min.js" charset="utf-8"></script>
<script type="text/javascript" src="/static/js/theme/jquery.flexslider-min.js?v=1" charset="utf-8"></script>

<style>


</style>
</head>

<body>
    <main>
        <!-- Header Section -->
        <section class="tophead" role="tophead"> 
        <!-- Navigation Section -->
        <header id="header">
          <div class="header-content clearfix"> <a class="logo" href="#">PRUEBA BANISTMO</a>
            <nav class="navigation" role="navigation">
              <ul class="primary-nav">          
                    <LI><a href="{% url 'accounts:logout' %}">Salir</a></LI>
              </ul>
            </nav>
            <a href="#" class="nav-toggle">Menu<span></span></a> </div>
        </header>
        <!-- Navigation Section --> 
      </section>
      <!-- Header Section --> 
      <section id="header-slider" class="section">
        
      </section>
{% block content %}
{% if user.is_authenticated %}
     

  <!-- Service Section --> 
  <section class="section services" >
        <div class="chart_container" align="center">
                <table class="chart_title">
                    <thead>
                        <tr>
                            <td colspan="4"> 
                                DETALLE DE TRANSACCIONES
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>     
                                                     
                                        <form name="myform" onSubmit="return handleClick()">
                                            <input name="Submit"  type="submit" value="Buscar Cliente" >
                                            <input type="text" id="myVal">
                                        </form>                        
                            </td>
                            <td>                                           
                                
                                <input type="checkbox" class="check" value="neto">
                                Mostrar Flujo de Caja Neto
                            </td>
                            <td>
                                    <input name="smaButton" class="button"
                                    type="button" 
                                    value="Mostrar Media Móvil" 
                                    onclick="showMovingAverage()" />
                            </td>
                            <td>
                                    <div class="alert" style="visibility: hidden">
                                            <span class="closebtn" onclick="hideAlert()">&times;</span>
                                            Media Móvil Calculada
                                    </div>  
                            </td>
                        </tr>  
                       
                    </tbody>
                    
                </table>
                
            </div>
        <br>
        <br>
        <script type='text/javascript' src='/static/js/visualize.js'></script>    
  </section>
  <!-- footer section -->
  
{% else %}
    <p><a href="{% url 'accounts:logout' %}">logout</a></p>
{% endif %}
<!-- JS FILES --> 
<script src="/static/js/jquery-3.2.1.min.js"></script> 
<script src="/static/js/theme/bootstrap.min.js"></script> 
<script src="/static/js/theme/jquery.flexslider-min.js"></script> 
<script src="/static/js/theme/retina.min.js"></script> 
<script src="/static/js/theme/modernizr.js"></script> 
<script src="/static/js/theme/main.js"></script>
</body>
</html>
{% endblock %}